# Generated by Django 5.0.6 on 2024-06-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='if_fired',
            field=models.BooleanField(default=False, verbose_name='Уволен'),
        ),
    ]
