# Generated by Django 5.0.6 on 2024-06-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('datecreation', models.DateField(verbose_name='Date Creation')),
                ('orderstatus', models.CharField(max_length=255, verbose_name='Order Status')),
                ('paymentstatus', models.CharField(max_length=255, verbose_name='Payment Status')),
                ('carelement', models.CharField(max_length=255, verbose_name='Car Element')),
                ('details', models.CharField(max_length=255, verbose_name='Details')),
                ('liquids', models.CharField(max_length=255, verbose_name='Liquids')),
                ('amountdamage', models.IntegerField(verbose_name='Amount Damage')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shiftid', models.AutoField(primary_key=True, serialize=False)),
                ('datestart', models.DateField(verbose_name='Date Start')),
                ('dateend', models.DateField(verbose_name='Date End')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, verbose_name='Login')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('middlename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userroleid', models.AutoField(primary_key=True, serialize=False)),
                ('namerole', models.CharField(max_length=255, verbose_name='Role Name')),
            ],
        ),
        migrations.CreateModel(
            name='OrderUserList',
            fields=[
                ('orderuserlistid', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.order')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('userlistid', models.AutoField(primary_key=True, serialize=False)),
                ('shiftid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.shift')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userrole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.userrole'),
        ),
    ]
